### ISSUE TITLE
Megamod doesn't launch with newest Win10 updates

### ISSUE THREAD

**Issue by Thomsonio** [JHGuitarFreak/UQM-MegaMod#103]
The topic tells it all :-/

**Comment by Serosis** [comment]
I can't replicate this issue.

Installed a fresh Windows 10, updated it, installed MegaMod, and it ran perfectly fine.
![Annotation 2022-03-13 114136](https://user-images.githubusercontent.com/4404965/158074405-f932d767-f022-41fa-bb78-3d7842441273.png)

**Comment by Thomsonio** [comment]
The first start time it worked after fresh installation. But second time and after it didn't (and for me still doesnt in win10). This happened after 2 fresh Win10 installations. Now it works in Win7 repetitively though.

**Comment by Serosis** [comment]
Starting to sound more like a Windows problem than a MegaMod problem since nothing is changing with MegaMod when it stops launching.

Is there any info you can give me about how/where you're installing MegaMod or what applications you're installing afterwards that may conflict with it?

**Comment by Thomsonio** [comment]
Yes, I would think windows updates breaks/blocks something. I suspected automatic updates right after installation, including windows defender. For example, there are numerous warnings before windows allows downloading and running the .EXE installation file for windows. I hope this helps at least a little. I will close this issue now, since my solution was to install it to Win7.

**Comment by Serosis** [comment]
Windows 10 is aggressively anti-downloaded apps.

But again, it still works for me, even on Windows 11.

Perhaps it's not the updates. But something else interfering with it running.
