### ISSUE TITLE
In some situations the secondary fuel ellipse extends beyond actual range

### ISSUE THREAD

**Issue by Serosis** [JHGuitarFreak/UQM-MegaMod#104]
![image](https://user-images.githubusercontent.com/4404965/159652302-bc280f98-0617-4fca-a412-68fbe61cc3d4.png)

![image](https://user-images.githubusercontent.com/4404965/159652464-7ec00c61-183a-41bf-9c16-a3875a981fe7.png)

**Comment by JHGuitarFreak** [comment]
This was fixed by using Malin's fuel ellipse code from their mod UQM-Roguelike.
