### ISSUE TITLE
Android game launch fail: can't access www.warpstormstudios.com

### ISSUE THREAD

**Issue by ballo** [JHGuitarFreak/UQM-MegaMod#107]
![Screenshot_20220514-174611_The Ur-Quan Masters MegaMod](https://user-images.githubusercontent.com/631311/168451589-c8a2ab2b-bb58-4252-9416-430891dae3e6.jpg)
Version 0.8.1

**Comment by ballo** [comment]
Could it be because the game is attempting to use https instead of http?

**Comment by JHGuitarFreak** [comment]
That does seem to be the case.

Uninstall and reinstall MegaMod but leave Soul Reaver's fixes unchecked.
You can download the fixes manually from [Soul Reaver's website](http://www.warpstormstudios.com/uqmmod/) and stick them in the `Android\data\net.serosis.megamod\files\addons` directory on the device.

**Comment by JHGuitarFreak** [comment]
Unfortunately the bad news is that the Android setup can *only* download from sites with a SSL certificate and Soul Reaver's website does not have one.

So I had no choice but to remove his add-ons from the downloadable packages from within the MegaMod Android setup.

**Comment by ballo** [comment]
Maybe include a good set of instructions on how to do it manually?
