### ISSUE TITLE
Missing image? 'base/nav/slaveshield-016.png'

### ISSUE THREAD

**Issue by Stephen2** [JHGuitarFreak/UQM-MegaMod#109]
Seen in console:
`Gfx Driver reports: Couldn't open 'base/nav/slaveshield-016.png': No such file or directory`

**Comment by JHGuitarFreak** [comment]
That can be ignored as it's just an erroneous entry. There is not supposed to be a `slaveshield-016.png`.

Fixed the issue with this commit over in the content repository: https://github.com/JHGuitarFreak/UQM-MegaMod-Content/commit/d39aa160f2802866e99eba6bc283fbf942c54cd5

**Comment by Stephen2** [comment]
Thank you
