### ISSUE TITLE
Syreen timestamps broken

### ISSUE THREAD

**Issue by Ala-lala** [JHGuitarFreak/UQM-MegaMod#11]
`we_are_vindicator0`, `1`, and `2`, and `WELCOME_VINDICATOR0`, `1`, and `2` were both merged into one line of dialogue thanks to Lua interpolation. However, the `.ts` file was not updated, making it fail to load.

(This is another issue that also affects base UQM, though only on the unfinished v0.8.0.)

**Comment by Serosis** [comment]
Nice find. I'll get on that.

**Comment by Serosis** [comment]
Fixed
