### ISSUE TITLE
Suggestion: no Hayes distortion option

### ISSUE THREAD

**Issue by onpon4** [JHGuitarFreak/UQM-MegaMod#113]
I was thinking, it might be a good idea to have an option (whether via a menu option or just via an alternative content pack) to disable the distortion to the Hayes voice clips before giving him radioactives, for accessibility. The main reason I'm thinking this is, the part where the distortion effect is applied is basically a tutorial section and if a new player either isn't very good at reading or just prefers not to have subtitles enabled, they might find it a bit difficult to follow along with what Hayes is saying. Plus it's entirely possible some players might prefer the original non-distorted voice for aesthetic reasons (similar to how some people might prefer the original graphics over the HD graphics). Distortion can still be the default I think (I imagine most players wouldn't have an issue and would prefer the distortion effect), but having an option would be nice.

**Comment by JHGuitarFreak** [comment]
I think we're getting pretty close to this being possible soon enough.  
Because I actually agree. The HD-mod dramatization can be a bit too much.

**Comment by JHGuitarFreak** [comment]
I think what I'm going to do is revert Hayes to vanilla audio and stick his distorted audio in its own addon or in the classic pack.

(Actually, let's do it as an Extended Lore option)

**Comment by JHGuitarFreak** [comment]
I'm going to close this as no distortion is now the default and I'm planning on making the distorted version a separate addon.

**Comment by JoshuaPettus** [comment]
Maybe include it in the "Classic HD graphics" addon since they were the ones to add it?
