### ISSUE TITLE
OSX Crash when fighting Orz

### ISSUE THREAD

**Issue by gpbrady31** [JHGuitarFreak/UQM-MegaMod#127]
Hi...I tried looking on the main UQM project page, but the bugzilla link for troubleshooting doesn't work...so I thought I ask here since this is where I downloaded it.

OSX Monterey 2016 macbook pro
0.8.1 megamod release

Game runs fine except i've pissed off the orz and now when I enter the battle the game crashes...doesn't seem to do this for other races. I even started a new game and went right away and tried to fight them, boom...crash.

It would be great if you could help.

**Comment by JHGuitarFreak** [comment]
I'll take a look into it. I *should* be able to get my iMac running either tomorrow or Sunday at the latest.

**Comment by Kruzen** [comment]
By any chance, any fight crash or specific one?

Can you pick ship before battle or it crashes right before that?

Also what settings do you use? Like SD/HD, scaler, melee zoom etc?

That would help to narrow down the problem.

Thanks!

**Comment by gpbrady31** [comment]
Hi...

It was any fight. It crashed right after I picked my ship to fight, and it
was any ship.

I actually figured out a work-around. I had a number of cheats turned on.
Once I turned them off, I was able to engage the Orz. Not sure if it was
the god mode one or not. I had the no objects turned on as well. Not sure
about the melee zoom. I also had the HD on and a higher resolution than
default.

I really appreciate your reply.

Thanks,
Geoff

**Comment by JHGuitarFreak** [comment]
Reproduced. It was the _No Melee Obstacles_ cheat and it crashes on Windows as well.

**Comment by gpbrady31** [comment]
Cool...glad you figured it out.

**Comment by JHGuitarFreak** [comment]
Fixed it with commit 1e189f8528a162ff43e6db59fc31b1c525ad7faf

But for now steer clear of fighting the Orz with the cheat enabled.
