### ISSUE TITLE
Scroll Style options don't work properly

### ISSUE THREAD

**Issue by Queenofdragons6** [JHGuitarFreak/UQM-MegaMod#133]
The Scroll Style options in PC/3DO options don't work as they should. "Per-Page" has it practically disabled, with the player only able to make dialogue skip forward but not go backwards. "Smooth" allows the player to go forwards and backwards, but it does so one screen of subtitles at a time instead of linearly. And the original UQM has the options work as stated, so it's got to be something in the MegaMod.

**Comment by Kruzen** [comment]
Hello! Do you have voices on or off? Because scrolling behave differently with voices disabled.

**Comment by Queenofdragons6** [comment]
Off, in both original UQM and MegaMod. Why does it behave differently?

**Comment by Kruzen** [comment]
In megamod per-page scroll with voices off mimics PC-DOS behaviour which didn't have scrolling back. That was intentional
