### ISSUE TITLE
[Graphics] 3DO planet have a black 1px dot in the middle

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#156]
![изображение](https://user-images.githubusercontent.com/68859542/205252822-45c3f8b5-5432-4560-8968-607b4bcc12f3.png)

This is probably because of dimensions and radial calculation of sphere mask - dead center doesn't get in

**Comment by JHGuitarFreak** [comment]
We can no longer replicate so closing this issue for now.
