### ISSUE TITLE
Thraddash do not notice stolen Aqua Helix

### ISSUE THREAD

**Issue by tymofij** [JHGuitarFreak/UQM-MegaMod#157]
1. Dominated the Thraddash and stole Aqua Helix from Zeta Draconis 1
2. Talked to them afterwards, they give no notice to the Aqua Helix theft
[Saves before and after theft.zip](https://github.com/JHGuitarFreak/UQM-MegaMod/files/10149444/Saves.before.and.after.theft.zip)

MegaMod 0.8.2, MacOS 10.15.7
Extended lore was disabled throughout the entire game.

PS. Thank you for the great game!

**Comment by Kruzen** [comment]
Fixed in #160
