### ISSUE TITLE
Bug: Can win game by bypassing final battle by using flagship and emergency warp escaping without destroying Sa-Matra

### ISSUE THREAD

**Issue by adigiuseppe** [JHGuitarFreak/UQM-MegaMod#161]
**Bug:** Can win game by bypassing Sa-Matra final battle by using flagship and immediately emergency warp escaping (<ESC> key), without destroying Sa-Matra. Final sequence plays out as if the Sa-Matra has been destroyed. (UQM MegaMod v0.82)

Discovered by Fabio Di Giuseppe

**Comment by Kruzen** [comment]
@adigiuseppe Hello. Weird behaviour considering that warp escape should be locked for flagship at this state. 2 questions:
1) Did you use HD graphics of classic?
2) Did warp-out animation played for flagship or it was just as simple "Press ESC to win the game" -> instantly to endgame cutscene?

**Comment by JHGuitarFreak** [comment]
The only way I can replicate this is by setting the difficulty to Easy Mode, in which case this is fully intended.

If you're not using Easy Mode then we'll need more information and a save file to debug the issue.

**Comment by JHGuitarFreak** [comment]
I'm going to close this until I've seen it duplicated.

**Comment by adigiuseppe** [comment]
You're right, I didn't realize my son was playing in Easy Mode. (Thanks for
your attention to this matter.)
