### ISSUE TITLE
Bug: (Linux) Selling Planet Landers Does Not Remove Sprite

### ISSUE THREAD

**Issue by ModeSelectStart** [JHGuitarFreak/UQM-MegaMod#162]
When selling planet landers on the outfit starship screen, the tiny sprites on the ship status panel on the right updated correctly, but the sprites on the main panel stayed there until completely leaving Outfit Starship screen.

Expected behavior: Lander sprites disappearing the same way thruster/turning jets and most(if not all) of the modules do.

Note: I had 4-5 landers when entering the Outfit Starship menu.
Platform: Garuda (Arch based) Linux
Graphics options: 3do graphics when available, textured+spinning planets.

**Comment by Kruzen** [comment]
@ModeSelectStart Hi, sorry for the late response. Does this happens to HD graphics or original? Or both maybe?

**Comment by ModeSelectStart** [comment]
@Kruzen apologies for my late response. The reported issue was with original graphics and I'm not currently able to replicate the behavior using HD graphics

**Comment by JHGuitarFreak** [comment]
I was able to replicate this
![2023-06-11_23-55-21 v0 8 3 MegaMod Debug](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/104330805/5f625c79-069a-4096-ab93-98551121726b)

I'll see what I can do

**Comment by JHGuitarFreak** [comment]
I fixed it on my end with commit 6483763
