### ISSUE TITLE
Documentation Update?

### ISSUE THREAD

**Issue by jdkruzr** [JHGuitarFreak/UQM-MegaMod#163]
Hi,

I'm on Mac and it's not at all clear how to use any of this -- the documentation suggests you can get a complete list of options by running the UQM binary with -h, but it segfaults when you try. I tried launching it with --addon and then the path to the mm content file, but that doesn't appear to do anything. Can we get some hints?

**Comment by JHGuitarFreak** [comment]
I have never tried to run MegaMod, nor UQM for that matter, as a plain binary on macOS.
I can only suspect that it would work the same as it does on Linux.

Anything you figure out you can reveal here and would be added to the documentation.

**Comment by JoshuaPettus** [comment]
Isnt uqm megamod for osx an app bundle?   I don't think JHGuitarFreak changed anything in the bundling process.  If so, I would look at the regular uqm instructions which state:
 Open up the app bundle (Right click, open package contents) and move the files to Contents/Resources/content/addons.

If its not an app bundle, and just a binary, it's probably looking for the addon files in the regular linux location which is set at compile (I always change it).

**Comment by JHGuitarFreak** [comment]
I'm just going to close this out with some comments from myself.

You can grab the current (as of June 12th, 2023) macOS (Intel only) version here: https://sourceforge.net/projects/uqm-mods/files/MegaMod/0.8.2/mm-0.8.2-macos-intel.dmg/download

If you are running macOS on Apple Silicon (either M1 or M2) then you'll have to clone this repository and build it yourself as I do not own anything newer than a 2010 iMac.

I'll also reiterate what is said in the README.md, which is that **MegaMod is standalone** and _completely incompatible with other mods, even Vanilla UQM_. It is not to be installed on top of any other version of UQM nor should you try to use the addons from MegaMod on other versions of UQM unless it is explicitly stated that they are compatible.

I'm sorry we couldn't help you getting it working in your instance but you left us little to go on and haven't responded in a few months.

**Comment by ylluminate** [comment]
Any chance we could get a Homebrew and MacPorts formula for quick building? Seems like a nice solution for macOS situations. The Intel binary could be available as a Cask, but the Apple Silicon could just be a source build.
