### ISSUE TITLE
Laser collision is broken in HD for some ships

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#165]
Most noticeably with Ilwrath Avenger. AFAIK it is not ship's sprite

![изображение](https://user-images.githubusercontent.com/68859542/234012883-be99b7e8-cda9-427d-8c1f-1305fc2d69b1.png)

**Comment by JHGuitarFreak** [comment]
Possibly fixed by commit 17c66d1
Closing for now
