### ISSUE TITLE
X-Form lasers should collide and spawn impact graphics

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#166]
In HD due to different values effect is lost

![изображение](https://user-images.githubusercontent.com/68859542/234013921-d0d829ee-6992-4cf2-886c-3d908a2545b6.png)

![изображение](https://user-images.githubusercontent.com/68859542/234014261-1f78ff7d-c32e-4326-ada8-8c5d46d4b721.png)

**Comment by JHGuitarFreak** [comment]
Possibly fixed by commit 17c66d1
Closing for now
