### ISSUE TITLE
Rainbow Worlds Map

### ISSUE THREAD

**Issue by HimoriK** [JHGuitarFreak/UQM-MegaMod#170]
Add a 'hidden' map for discovered rainbow worlds, for backtracking and aesthetics.

**Comment by JHGuitarFreak** [comment]
This was easy enough since I already had a map that showed all Rainbow Worlds from before. Just gave it a couple tweaks and here you go:
![2023-06-13_09-33-02 v0 8 3 MegaMod Debug](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/104330805/df93240b-7d60-4c83-b0c6-58434f664a7d)

commit ee47619
