### ISSUE TITLE
Building with VS isn't as easy as the README says it is

### ISSUE THREAD

**Issue by Ala-lala** [JHGuitarFreak/UQM-MegaMod#2]
Building it with VC++ 2008 works fine; however, building it with VS2019 requires you to either:

* Accept the platform toolset upgrade to v142 (and the SDK upgrade if you only have the Windows 10 SDK) at startup (or use "Retarget solution" later) and add the VS2015 dev-lib paths to the additional include and library directories (by far the easiest way)
* Install both VC++ 2008 [*and* VC++ 2010](https://stackoverflow.com/a/13226528) - if you don't have both installed, it'll give you this error:
>error MSB8020: The build tools for Visual Studio 2008 (Platform Toolset = 'v90') cannot be found. To build using the v90 build tools, please install Visual Studio 2008 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

**Comment by Ala-lala** [comment]
I don't have much experience with Visual C++, so I don't know if changing the platform toolset has any adverse side effects (other than breaking libraries, which you already dealt with), but if it doesn't, I'd suggest changing the included VS2019 project's platform toolset to v142 and making it use the VS2015 dev-libs.

**Comment by Serosis** [comment]
The problem with that being is that using anything past the 2008 toolset breaks net-code functionality. (It's already on the radar of one of the core UQM devs)

I'm planning on including build targets within the 2019 solution file that includes both the 2008 toolset targeting and whatever modern version I have. Possibly replace the "NoAccel" build targets seeing as they're beyond moot now that UQM can be built on something a bit more modern than Visual Studio 6.

I should just edit the readme to say VS2008 solution files are bulletproof building while 2019 still needs work.

**Comment by Serosis** [comment]
Updated the Readme.md to reflect the degree of difficulty setting up VS2015-2019. 

How's that look?

(sometimes I forget the fact that you have to have both 2008 and 2010 installed to get 2008 as a targetable toolset in VS2015-2019)

**Comment by Ala-lala** [comment]
Looks good (though you have three minor typos: "additional library and lib directories", "equivilent", and "fucntionality")
