### ISSUE TITLE
This happens when I run the executable

### ISSUE THREAD

**Issue by GlowbroWackys** [JHGuitarFreak/UQM-MegaMod#207]
**_### (IGNORE THIS I FOUND OUT THE ISSUE, SORRY IF I WASTED ANYONES TIME!)_**
![image](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/154816207/3fde0448-0789-4825-a008-35e3afae48db)
Not sure why this happens, but it seems to only happen on windows 11

**Comment by GlowbroWackys** [comment]
forgot to add the label, but I believe this is a bug

**Comment by JoshuaPettus** [comment]
Most certainly it is not.  It looks to  be an issue with your setup.  Maybe you are missing a runtime?

[EDIT]  Just saw the note on your first post.  Perhaps you should close the ticket?

**Comment by JHGuitarFreak** [comment]
Good ole Windows trying to assume your intentions.

Marking as closed.
