### ISSUE TITLE
min and max are only defined by default in visual studio.

### ISSUE THREAD

**Issue by Kokokokoka** [JHGuitarFreak/UQM-MegaMod#21]
```
obj/release/src/libs/sound/mixer/mixer.c.o: in function `mixer_Sourcefv':
mixer.c:(.text+0x19e6): undefined reference to `max'
collect2: error: ld returned 1 exit status
```
this helps: ./src/libs/sound/mixer/mixer.c
```
#ifndef MAX
#define min(X,Y) (((X) < (Y)) ? (X) : (Y))
#define max(X,Y) (((X) > (Y)) ? (X) : (Y))
#endif
```

**Comment by Serosis** [comment]
Took me awhile to get to it but I added definitions for min/max above the (mixer_Sourcefv) function when Visual Studio is out of the picture.

I can get this fixed properly in the future once I get back into the swing of things.

**Comment by Kokokokoka** [comment]
Thank you! I've got a problem with saving config files on Linux. 
Will report this later.
