### ISSUE TITLE
Screen slightly cut off 

### ISSUE THREAD

**Issue by glhf2** [JHGuitarFreak/UQM-MegaMod#226]
![screen slightly cut off bottom and top](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/162784098/f37ab8ea-6db7-40d0-a32a-7c6991cd7802)

Hi, I don't know why but my screen is slightly cut off at the top and bottom. If someone's already had this issue and got it fixed, let me know. Or if y'all got any suggestions.

**Comment by JHGuitarFreak** [comment]
You have to set the resolution manually to fit within your screen size in the setup menu.
![2024-03-09_15-36-20 v0 8 2 MegaMod](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/104330805/6a1b627b-7a52-44b1-8661-b8fb6a1d8692)

**Comment by glhf2** [comment]
![resolved](https://github.com/JHGuitarFreak/UQM-MegaMod/assets/162784098/c9afd41f-a3e8-4a51-8a18-67b9439ad27d)
Thanks! I'm not sure why but changing the original/HD, nor the resolution, didn't really fix the issue. Making it full screen, however, did the trick for me. :]
