### ISSUE TITLE
Urquan Drone doesnt appear in new game  0.8.0.85 master build

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#23]
Hi. I did a test build of your master branch. I know it's not ready yet, but I thought I'd give it a try.  I also took the latest master build of your uqm content.  I built in Linux and against SDL2, with all the addons active, in case that is relevant.  Anyway I started a new game and went to earth and the Urquan drone didn't appear.  Happens in both HD and SD.

Thought you should know.

**Comment by Serosis** [comment]
Ah, that must be a malfunction in the code I used for the Head Start cheat.

**Comment by Serosis** [comment]
I fixed it by removing the code that disables the Probe when Head Start is enabled.

I shouldn't have tried to disable that in the first place since it's a plot event.
