### ISSUE TITLE
Hardmode crash with Probe encounter

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#239]
Slylandro battle groups that are spawned around rainbow worlds in Hardmode aren't properly serialized, which leads to game crash on encounter initialization after Save/Load.
Steps to reproduce:

1. Start a game in Hardmode
2. Go to Rainbow world system
3. Save game
4. Load saved game
5. Go to probe withing that system

**Comment by Kruzen** [comment]
Bug was partially described in #201 but there were no evidence what caused it. So far it is NOT fixed.

**Comment by JHGuitarFreak** [comment]
Fixed with commit [8daacb6](https://github.com/JHGuitarFreak/UQM-MegaMod/commit/8daacb6b04b85f99f317a393253146858e0c724f)

Past saves are still shit outta luck but the problem will not present itself from here on out.
