### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by electronstudio** [JHGuitarFreak/UQM-MegaMod#242]
There's a link on https://uqm-mods.sourceforge.net/Download to https://sourceforge.net/projects/uqm-mods/files/MegaMod/0.8.3/Content/mm-0.8.3-hd.uqm . I think it should be https://sourceforge.net/projects/uqm-mods/files/MegaMod/0.8.3/Content/mm-0.8.3-hd-content.uqm ?

**Comment by JHGuitarFreak** [comment]
Nice catch!

Fixed.
