### ISSUE TITLE
Another broken link

### ISSUE THREAD

**Issue by Queenofdragons6** [JHGuitarFreak/UQM-MegaMod#243]
Looking at the [Download](https://uqm-mods.sourceforge.net/Download) page, trying to download the [Alternate Remix pack Hyper/Quasispace themes by Mark Vera](https://sourceforge.net/projects/uqm-mods/files/MegaMod/0.8.3/Content/uqm-remix-hqspace.uqm) takes me to the main download page with a pop-up that says, "The "/MegaMod/0.8.3/Conte..qm-remix-hqspace.uqm" file could not be found or is not available. Please select another file."

**Comment by JHGuitarFreak** [comment]
Fixed!
