### ISSUE TITLE
Game Crashes/Client Closes when Chmmr send me back to Sol to affix the bomb to ship.

### ISSUE THREAD

**Issue by Djurkwhad** [JHGuitarFreak/UQM-MegaMod#245]
Playing through v 0.8.3

Near completing the game, I complete the dialog with the Chmmr to have the bomb affixed to the ship, and upon ending the conversation, the client crashes. 

Windows logs:
Faulting application name: UrQuanMasters.exe, version: 0.8.1.0, time stamp: 0x66182ecf
Faulting module name: UrQuanMasters.exe, version: 0.8.1.0, time stamp: 0x66182ecf
Exception code: 0xc0000094
Fault offset: 0x0017f78b
Faulting process id: 0x0x2AB4
Faulting application start time: 0x0x1DA9F29017EE44A
Faulting application path: C:\Games\The Ur-Quan Masters MegaMod\UrQuanMasters.exe
Faulting module path: C:\Games\The Ur-Quan Masters MegaMod\UrQuanMasters.exe
Report Id: c8582244-b672-465c-baaa-8c12fc347fdf
Faulting package full name: 
Faulting package-relative application ID: 

------------------
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: UrQuanMasters.exe
P2: 0.8.1.0
P3: 66182ecf
P4: UrQuanMasters.exe
P5: 0.8.1.0
P6: 66182ecf
P7: c0000094
P8: 0017f78b
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_UrQuanMasters.ex_6d336223c3996fcee27433b63516639c93e54f7_8fdd8e84_a2d7ad60-4472-4653-b5fa-569d7535256c

Analysis symbol: 
Rechecking for solution: 0
Report Id: c8582244-b672-465c-baaa-8c12fc347fdf
Report Status: 4
Hashed bucket: 
Cab Guid: 0

--------------

Fault bucket 1838292305495111618, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: UrQuanMasters.exe
P2: 0.8.1.0
P3: 66182ecf
P4: UrQuanMasters.exe
P5: 0.8.1.0
P6: 66182ecf
P7: c0000094
P8: 0017f78b
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7e9804c3-8eb9-475c-8d69-f0c8c461bd81.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_UrQuanMasters.ex_6d336223c3996fcee27433b63516639c93e54f7_8fdd8e84_a2d7ad60-4472-4653-b5fa-569d7535256c

Analysis symbol: 
Rechecking for solution: 0
Report Id: c8582244-b672-465c-baaa-8c12fc347fdf
Report Status: 268435456
Hashed bucket: 485e3fb683c45127e982ed1cb65eb7c2
Cab Guid: 0

**Comment by JHGuitarFreak** [comment]
Do you have a save file from right before the bomb is attached?

**Comment by Djurkwhad** [comment]
I can upload, sure. Where do I find it?

**Comment by JHGuitarFreak** [comment]
It'll be tucked away in the AppData directories...

`C:\Users\[YOUR USERNAME]\AppData\Roaming\UQM-MegaMod\save`

**Comment by Djurkwhad** [comment]
[uqmsave.zip](https://github.com/JHGuitarFreak/UQM-MegaMod/files/15214536/uqmsave.zip)

**Comment by JHGuitarFreak** [comment]
Awesome, we have an orbit drawing bug on top of a textured planet bug.  
Or this could be a bug in the custom seed when it's set too low. We never really did extensive testing for those scenarios.

I've managed to bypass the bug itself and made you a save after the bomb is attached.
[uqmsave.zip](https://github.com/JHGuitarFreak/UQM-MegaMod/files/15214568/uqmsave.zip)

Hopefully no more bugs show up while you finish the game.

**Comment by Djurkwhad** [comment]
Amazing, thanks for such a quick workaround!

**Comment by JHGuitarFreak** [comment]
No problem, we'll keep this bug report up until it is properly fixed.

**Comment by Kruzen** [comment]
Fixed in #249
