### ISSUE TITLE
HD: Animation bug while using SDL2 builds

### ISSUE THREAD

**Issue by Serosis** [JHGuitarFreak/UQM-MegaMod#25]
Seems in SDL2 the animation frames aren't clearing properly for the Earth Starbase leading to black lines around the animated frames that build up over a period of time.

![image](https://user-images.githubusercontent.com/4404965/72265753-e4b92f80-35d1-11ea-865f-afd8ee12d6ec.png)

This does not happen in either SDL1 in HD nor in SDL2 in SD so it may actually be a problem with the animation content itself.

**Comment by JoshuaPettus** [comment]
Yup I can confirm that this is in my linux test build I made with SDL2.   Didn't notice at first as first! XD

**Comment by Serosis** [comment]
Definitely not the content as it's the exact same animation frames from the HD-Mod.

So something is not clearing the animation properly.

**Comment by Serosis** [comment]
Fixed this by remasking and tightening up the Starbase animation files.
![image](https://user-images.githubusercontent.com/4404965/72687560-ceb8dc80-3ab3-11ea-83da-09aae8bdb05a.png)

**Comment by Serosis** [comment]
Reopening this issue because it happens with the Umgah and the Shofixti as well.

Hopefully I can find a way to fix it without having to remask all the affected animation files.

EDIT:

Druuge and Arilou also have the bug.

**Comment by Serosis** [comment]
After talking with McMartin it seems to be a pixel transparency issue where SDL2 is having an issue with alpha transparency blending. I can easily remove all transparent pixels from affected animations but I would like to find out where SDL1 and 2 differ in this case in the code.

**Comment by Serosis** [comment]
After rescaling UI and most of the HD animations this is no longer an issue per se but still an issue if you want animations with half transparencies. Closing it for now since it no longer affects the MegaMod.
