### ISSUE TITLE
Android (disabling overlays)

### ISSUE THREAD

**Issue by occultknowledge** [JHGuitarFreak/UQM-MegaMod#250]
I am using a gamepad and I can’t see my ship flying through the swirly control overlays. I don’t need the overlays. How can I get rid of them. Nothing works!

**Comment by JHGuitarFreak** [comment]
There's a button you can press when the game first opens on Android where there's an option that gives you the ability to adjust the transparency of the overlays

**Comment by JHGuitarFreak** [comment]
Closing as I've not heard a response for months and this is a trivial non-issue that can be solved by looking through the pre-game options.
