### ISSUE TITLE
Pedantic patch

### ISSUE THREAD

**Issue by DanSorrell** [JHGuitarFreak/UQM-MegaMod#253]
I’m building with the latest GCC compiler using the -= Main menu =- option of:
1. Type of build = 1. Optimised release build.

My compiler refuses to build without applying [Patch.zip](https://github.com/user-attachments/files/16567548/Patch.zip).  Maybe it will let this game compile if I crippled my compiler to an older version of the C standard.  I think it’s better to just update the master branch to modern standards.

**Comment by JHGuitarFreak** [comment]
No worries. Applied the patch and nothing exploded so pushed to master with commit 1512e94

**Comment by DanSorrell** [comment]
Also should have included this:

./src/uqm/setupmenu.c

Change line 2389

From:

PutIntOpt (&optMusicResume, &opts->musicResume, "mm.musicResume", FALSE);

To:

PutIntOpt (&optMusicResume, (int*)&opts->musicResume, "mm.musicResume", FALSE);

**Comment by JHGuitarFreak** [comment]
Added
