### ISSUE TITLE
Running through Steam as SC1&2

### ISSUE THREAD

**Issue by TheWranger** [JHGuitarFreak/UQM-MegaMod#26]
It would be nice to be able to run the MegaMod as an alternative to the normal dosbox package of SC1&2 on Steam so that playtime can still be tracked, but it doesn't seem to launch; supposedly because the Steam release adds a launch argument that is designed for DOSBox but is invalid in UQM.

Would it be possible for a workaround for this launch argument to be added, or perhaps some option that makes the game ignore invalid launch arguments and launch anyway (unless that already exists and I'm missing it)?
![untitled](https://user-images.githubusercontent.com/24642838/73043410-ba5c5180-3eb0-11ea-8662-ff7ac8f3ae53.jpeg)

**Comment by JoshuaPettus** [comment]
I don't understand why you are trying to replace the steam executable for SC1+SC2.  What you should do is add MegaMod as a non-steam game,  you will get all such features and the ability to add the steam controller.

**Comment by TheWranger** [comment]
You aren't able to track playtime if you add UQM as a non-steam game

**Comment by Serosis** [comment]
Unfortunately UQM is already using the commandline argument that Steam is using against DOSBox. Which is `-c`.

I could easily get -noconsole in there but not -c.

**Comment by TheWranger** [comment]
Shame, nevermind then. Thanks anyway
