### ISSUE TITLE
build for Android?

### ISSUE THREAD

**Issue by Duron27** [JHGuitarFreak/UQM-MegaMod#260]
not finding any info on building with the ndk. is it documented somewhere?

**Comment by JHGuitarFreak** [comment]
It isn't officially supported and there is no real documentation. The builds that exist for Android are based off of the commandergenius SDL wrapper by pelya where I extrapolate the steps needed to build UQM and UQM-HD for Android: https://github.com/pelya/commandergenius

It will remain unsupported for the foreseeable future until I can understand how to build it myself without relying on any kind of wrapper.

Closing the issue as it's more a question than an actual issue.

**Comment by Duron27** [comment]
Oh sorry i didn't see this.  I'll try to figure it out. If I get anywhere I'll pass it along
