### ISSUE TITLE
0.8.0.85 alpha - 1x ocillascope is barely visiable

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#28]
Hi,  did another test build of where the code is at now with megamod and current content. (Love where its at and going :))  Anyway,  I noticed that in 1x graphics mode the oscilloscope audio meter in the lower right corner during conversations is barely visible.   Just thought you'd like to know if you haven't seen that bit yet.

Not sure if it's another SDL2 issue or not. I haven't tried SDL1 yet

**Comment by Serosis** [comment]
Do you have a screenshot?

Because on my end it looks completely normal: 
![image](https://user-images.githubusercontent.com/4404965/76526261-7d312c00-642a-11ea-8fd2-d584c2c8b090.png)

**Comment by JoshuaPettus** [comment]
Weird I suddenly can't reproduce it anymore.  Maybe I'm just crazy...

**Comment by JoshuaPettus** [comment]
I'll chalk this one up to too much wine last night....  If I ever do reproduce it again I'll be sure to get you that screenshot.  In the mean time I'll close this for now.
