### ISSUE TITLE
Seeded Starmap "4040404" crashes entering Alpha Vulpeculae

### ISSUE THREAD

**Issue by TrophySystem** [JHGuitarFreak/UQM-MegaMod#29]
Seeded Starmap "4040404" crashes entering Alpha Vulpeculae (center of green hexagon starcluster), windows 10, most recent version of megamod, all optional content from the pack (sans japanese localization)

On that note, the game crashes with "out of memory" several times if exploring various star systems longer than a hour and a half. Doesn't reproduce on load, so it's likely a memory leak?

**Comment by Serosis** [comment]
Indeed it does. Not even a proper crash but a full lockup. Doesn't even get to the debugger.

EDIT: I have a general idea of what's causing it though the solution might break a few saves.

**Comment by TrophySystem** [comment]
I'm intrigued and glad I could help. I was interested in randomization to the game before I found the megamod to be honest, so it was rather interesting to check it out!

What's the best way to contact you if I was interested in more details on it btw?

**Comment by Serosis** [comment]
If you have Discord the MegaMod has its own channel in the Star Control fan server: https://discord.gg/TFrQnY

**Comment by Serosis** [comment]
Fixed by rolling back max planet/moon changes for custom seeds.
