### ISSUE TITLE
Linux libraries not found  

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#32]
When trying to build from master on Ubuntu 20.04 suddenly ogg and vorbis libraries aren't found thereby disabling ogg support also It can't find the platform specific network libraries which disables multiplayer.  And a few others including zlib and tremor.   This is not the case with the last stable build.  There everything was detected there

Here is the build script output

> ./build.sh uqm config
>'echo -n' capable echo found.
>Sed stream editor found.
>tr found.
>Make found.
>GNU C compiler found.
>We have a C preprocessor.
>We have a C dependency generator.
>We have a C compiler.
>We have a C++ preprocessor.
>We have a C++ dependency generator.
>We have a C++ compiler.
>We have a linker.
>Little-endian machine detected.
>Simple DirectMedia Layer version 1.2.15 found.
>Simple DirectMedia Layer version 2.x found.
>libpng found.
>Symbol 'readdir_r' found.
>Symbol 'setenv' found.
>Symbol 'strupr' not found.
>Symbol 'strcasecmp' found.
>Symbol 'stricmp' not found.
>Symbol 'acos' not found.
>Symbol 'iswgraph' found.
>Type 'wchar_t' found.
>Type 'wint_t' found.
>Symbol 'getopt_long' found.
>Header 'regex.h' found.
>Header 'regex.h' found.
>Symbol 'regcomp' not found.
>Type '_Bool' not found.
>Preprocessor macro 'WIN32' not found.
>Preprocessor macro '__MINGW32__' not found.
>pkg-config found.
>vorbisfile not found.
>tremor not found.
>Platform-specific network libraries not found.
>zlib not found.
>
>  -= Main menu =-
>   1. Type of build                        Debugging build
>   2. Graphics Engine                      SDL2 with modern graphics support
>   3. Sound backend                        Use MixSDL for sound (internal)
>   4. Tracker music support                Included libmikmod
>   5. Lua scripting                        Included Lua library
>   6. Ogg Vorbis codec                     No Ogg Vorbis support
>   7. Network Supermelee support           disabled
>   8. Joystick support                     enabled
>   9. Supported file i/o methods           Only direct file i/o
>  10. Graphics/Sound optimizations         Platform acceleration (asm, etc.)
>  11. Thread library                       SDL-controlled thread library
>  12. Installation paths                   [...]
>

**Comment by Serosis** [comment]
Yeah, that might be a holdover from McMartin's decision to switch Core UQM over to MSYS2. I kinda left it half-broken so I could keep MinGW support.

**Comment by JoshuaPettus** [comment]
:( anyway to put the changes behind some sort of if MingGW than statement?

**Comment by ajshell1** [comment]
I'm also getting these issues with Arch Linux. :(

EDIT: This method seems to work, if you don't mind installing Flatpak: https://github.com/rlac/flatpak-uqm-megamod

**Comment by Serosis** [comment]
I'll just re-push the Core UQM changes again since I'm not using MinGW right now.

EDIT: Actually I'm going to hold off on that.

Can you revert this commit yourself to see if it works:
https://github.com/Serosis/UQM-MegaMod/commit/079ed526b5be129024551a20689aa752052e242b

**Comment by JoshuaPettus** [comment]
Yup that would fix it.  Though you would say that would break MinGW?  That's a shame...

**Comment by Serosis** [comment]
I just need to get off my ass and write up a tutorial for MSYS2.

**Comment by JoshuaPettus** [comment]
Well this issue is fixed and working great.  I'll mark it closed.

Thanks Serosis,  love where this project is going.
