### ISSUE TITLE
Kruzenshtern's Bugs: SIS Title draws letters for moons (-A, -B e.t.c) in HD while in conversation with Syreen, or while reading report from orbit on any Extended Lore addon StarBase.

### ISSUE THREAD

**Issue by Serosis** [JHGuitarFreak/UQM-MegaMod#34]
A gentleperson named Kruzenshtern got in touch with me and sent me a lovely list of bugs that I'm entering in here so they can be tracked proper.

This is their second bug, verbatim:

According to changelog on git, it has been fixed. However I want to focus on the sidenote here.

#### ~~solarsys.c, funtion static void EnterPlanetOrbit (void). Change OR condition to AND condition.~~
![image](https://user-images.githubusercontent.com/4404965/88274211-2ec15300-cc90-11ea-90e7-3b4c804309bc.png)

_Sidenote_: it is possible to remove HD check, since there IS a room to draw at 320x240 with “widest” planet number – VIII. (Though looks a bit scuffed and maybe I’m wrong)
![image](https://user-images.githubusercontent.com/4404965/88274249-3da80580-cc90-11ea-9052-a2e09cc2ab28.png)
> Test for moon letter in SD with 320x240 (original) resolution 
Beta Hyginus – Star, that have eighth planet with moons

**Comment by Serosis** [comment]
Sidenote taken care of in commit [413a2a](https://github.com/Serosis/UQM-MegaMod/commit/413a2ab092aa13a22e405840c49310dacd81477e)

**Comment by Kruzen** [comment]
If it ever comes up again - Alpha Trianguli is a better place for testing. Planet VIII have all 4 moons instead of 2 at Beta Hyginus

**Comment by Serosis** [comment]
Planet VIII-D is a perfect fit so no problem.
