### ISSUE TITLE
Kruzenshtern's Bugs: SIS sprite draws twice during smooth interplanetary transition

### ISSUE THREAD

**Issue by Serosis** [JHGuitarFreak/UQM-MegaMod#39]
A gentleperson named Kruzenshtern got in touch with me and sent me a lovely list of bugs that I'm entering in here so they can be tracked proper.

This is their seventh bug, verbatim:

This bug will be shown in original graphics, but it also exists in HD. By interplanetary transition I mean transition in outer System. (approaching planets works fine)

#### Steps to reproduce:
Optional: get full thrusters and turning jets. The bug is more noticable with higher SIS velocity
⦁	Set IP Transition in game options to Smooth like in 3DO
⦁	Enter any system
⦁	Get max speed by flying to star
⦁	Turn 90 degrees in any direction (not nessessary but more noticable)
⦁	Wait for screen to start transition
⦁	PAUSE game right after transition starts
![image](https://user-images.githubusercontent.com/4404965/88281551-be6cfe80-cc9c-11ea-82e2-10c1cd6305e1.png)
> SIS sprite draws twice while approaching star 

This effect also can be seen when getting away from the star. This bug caused by 2 additional `IP_Frame()` calls in **solarsys.c**. When transition begins, `IP_Frame()` calls `ScaleSystem(SIZE newRadius)`, which calls `DrawOuterSystem(void)`.
![image](https://user-images.githubusercontent.com/4404965/88281616-de042700-cc9c-11ea-9b61-f73b7ca67c33.png)
> Part of ScaleSystem() function code

`DrawOuterSystem(void)` calls `IP_Frame()` and `DrawSystem (SIZE radius, BOOLEAN IsInnerSystem)`, which also calls `IP_Frame()`. If we remove these calls, the problem will be fixed, but it will cause another problem, which these calls were fixing – Star corona flickering and rotating planet textures in HD mode while transitioning. So this is not a solution.

### Possible solution
Remode `RedrawQueue (FALSE)` call from `ScaleSystem(SIZE newRadius)`:
![image](https://user-images.githubusercontent.com/4404965/88281745-0b50d500-cc9d-11ea-93dc-2f4e130e6afc.png)
With that fix SIS stops being drawn twice and Star corona along with planet textures in HD are OK. All mentioned functions are in **solarsys.c**.
_Sidenote_: while we are on topic about stars, can we edit sprite for star in SD? When nebulae option is on, sometimes stars have weird black circle around their edge
![image](https://user-images.githubusercontent.com/4404965/88281797-23285900-cc9d-11ea-9b01-ace2bfb888c7.png) - I got this image from UQM HD (for some reason)
![image](https://user-images.githubusercontent.com/4404965/88281831-33d8cf00-cc9d-11ea-966c-4a4e608fa76f.png)
> It’s barely visible, but simetimes it draws attention

**Comment by Serosis** [comment]
Nothing I can really do about the Suns without creating a set of Suns for each color.

As for fixing the double draw, I'll remove `RedrawQueue (FALSE)` temporarily, but I don't like removing code that's been there since the beginning.

Fixed with commit [e2c3310](https://github.com/Serosis/UQM-MegaMod/commit/e2c33100df96c1f8a12ead56c99c9c7fe8f6a775)

**Comment by Kruzen** [comment]
Hello there! Good job fixing these bugs so quickly!
I also don't like that, so I've come up with another possible solution for you to check out.

Step 1:
Move all Star/fancy planets related code from IP_Frame() to new function (including frameCounter variable):
![image](https://user-images.githubusercontent.com/68859542/88554046-ac89b380-d02e-11ea-8657-32a58690f822.png)
Step 2:
Call it in IP_Frame():
![image](https://user-images.githubusercontent.com/68859542/88554201-e65aba00-d02e-11ea-91c0-6b919ce6d8f7.png)
Step 3: Also call it in ScaleSystem(SIZE new_radius) along with RestoreSystemView():
![image](https://user-images.githubusercontent.com/68859542/88554560-549f7c80-d02f-11ea-9c29-03cd3d63e375.png)

I tested it, and it looks fine, without any visible frame drops, but the final decision is up to you. 

As for the star sprites - that's fine. It's mostly a nitpicking anyway.

**Comment by Serosis** [comment]
Yeah it has to do with the images not having any half transparent pixels, it's either transparent or not.  
Which is also why it's not a problem in HD because those guys made images for every color of Sun.

I'll take a look into the new fix. So far nothing bad is happening with commenting out `RedrawQueue()`.
If it's that simple of a fix I'll keep it that way.
