### ISSUE TITLE
Kruzenshtern's Bugs: Loading game in HD spits you out into HyperSpace

### ISSUE THREAD

**Issue by Serosis** [JHGuitarFreak/UQM-MegaMod#42]
A gentleperson named Kruzenshtern got in touch with me and sent me a lovely list of bugs that I'm entering in here so they can be tracked proper.

This is their tenth bug, verbatim:

Only if you saved at system entry.
#### Steps to reproduce:
⦁	Set graphics mode to HD
⦁	Start a new game
⦁	DO NOT MOVE
⦁	Save game
⦁	Load saved game
I’ve tried to change entry point on Y axis in HD a bit higher and it helps. But if you change back to SD and load game saved on step 4 – SIS will be drastically moved, which is unacceptable.
So probably change something when we load a game, like not get teleported instantly, but also not something easily abused like skipping encounters on save/load. I don’t have any more suggestions.

**Comment by Serosis** [comment]
There's currently nothing feasible I can do for this without restructuring the HD UI to be an exact 4x replica of Core UQM's UI.  
Currently it's a pseudo 4x with a lot of 3x elements.

This is on my list of things to do eventually but it's a major undertaking in recreating a lot of HD graphics.

**Comment by JoshuaPettus** [comment]
Perhaps you should look into AI upscaling which is all the rage these days.  The results can be impressive.  But then going from 3x to 4x isn't all that much.  Maybe just a simple trilinear filter upscale?   The game does it that way anyway on the fly, doesn't it?  So where is the quality loss if you do it before hand?

**Comment by Serosis** [comment]
Nah. I have all of the .psd files I used for MegaMod-HD and it would only require minor tweaks to the remaining HD-mod files to get things in line.

The biggest hurdle would be realigning everything in the code.

**Comment by JoshuaPettus** [comment]
Ah, of course

**Comment by Serosis** [comment]
After rescaling everything this bug has reared it's ugly head again. Only this time it's when you save in SD and load in HD.

**Comment by Serosis** [comment]
Commit ad16a8714d2eeb479dc1249998f6628929332908 fixes this bug.
