### ISSUE TITLE
Kruzenshtern's Bugs: Loading game on planet in inteplanetary freaks game out

### ISSUE THREAD

**Issue by Serosis** [JHGuitarFreak/UQM-MegaMod#43]
A gentleperson named Kruzenshtern got in touch with me and sent me a lovely list of bugs that I'm entering in here so they can be tracked proper.

This is their eleventh bug, verbatim:

Graphics mode doesn’t matter. Not an issue in original

#### Steps to reproduce:
⦁	Enter Interplanetary
⦁	Fly to any planet
⦁	Enter Inner system
⦁	Fly out of inner system (at this point outer system is drawn, SIS positioned on a planet sprite and it’s velocity is 0)
⦁	DO NOT MOVE
⦁	Save game
⦁	Load saved game
⦁	Game has a small seizure
⦁	Game spits SIS into inner system and SIS Title draws star coordinates

Probably tweak save/load mechanism again.

**Comment by Kruzen** [comment]
Found possible solution:

**solarsys.c**, function CheckIntersect(BOOLEAN just_checking):
Add following "else" code:
![image](https://user-images.githubusercontent.com/68859542/88556221-713cb400-d031-11ea-8255-35dea97f90eb.png)

When game is loaded or player entering a system - InitSolarSys(void) is called. Through the hierarchy of calls - CheckIntersect is called also. In our scenario collision with a planet is found (while entering the system doesn't so nothing is broken), but the game doesn't do anything with it, so first IP_Frame call starts transition into inner system. By adding these lines, transition will be ignored until we stop colliding with a planet.

Tested Save/Load, leave/enter star system, approaching different planets, orbiting planets option on/off and just regular flying around. Looks like it's working fine.

**Comment by Serosis** [comment]
I found the offending code. Going through the motions of fixing it now.

Fixed with commit [9d5f6f](https://github.com/Serosis/UQM-MegaMod/commit/9d5f6fe37dc4fcbbbbeb6e7b021a3f861c00b9a1)
