### ISSUE TITLE
A suggestion related to a constellation map

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#46]
The game has a fancy constellation map (press F7 twice). However zoom-in breaks it:

![image](https://user-images.githubusercontent.com/68859542/88559615-b5ca4e80-d035-11ea-8548-8dc72beee652.png)

I think it requres fixing (probably rescaling) but as a temporal solution: turn constellations off as we zoom in. And turn this feature off completely in original graphics (IMO it looks awful there)

![image](https://user-images.githubusercontent.com/68859542/88560029-42750c80-d036-11ea-839c-c0e8fe2ab46d.png)

**Comment by Serosis** [comment]
I know about this and I don't really know of a solution that's any good besides removing the constellations altogether.  
They don't really achieve anything special or helpful. But a completely blank StarMap could be helpful for the times when the on-screen SOI display and race names get in the way of finding certain stars.

**Comment by Kruzen** [comment]
Well, won't miss it anyway. Fixed.
