### ISSUE TITLE
StarMap scrolls up on max zoom-out

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#47]
Apparently, after fixing #38 starmap got broken again. It scrolls up even in max zoom-out. **Only** in HD and **only** in that direction.

![image](https://user-images.githubusercontent.com/68859542/89553887-c8533d80-d816-11ea-9ae5-633988c7e0e2.png)

I suggest to return deleted code to `UpdateCursorLocation ()` but with extra condition for zoom level check.
```
if (s.origin.y < 0 && zoomLevel == 0) 
	{
		s.origin.y = 0;
		cursorLoc.y = DISP_TO_UNIVERSEY (0);
        } 
```
I tested this solution and it works as intended.

**Comment by Serosis** [comment]
Applied in commit 7c275d34e5c431b81a6af603a91f13ef2d031d75
