### ISSUE TITLE
cannot zoom starmap on laptop

### ISSUE THREAD

**Issue by nsklaus** [JHGuitarFreak/UQM-MegaMod#49]
i'm playing uqm-mm on my laptop but, i cannot zoom in and out of starmap. i have no number key pad.
unless i'm mistaken, for those who do have a number keypad, that's where the +plus and -minus keys are located, is that right ? here, i have an "azerty" keyboard, so i must keep pressing shift to type a plus sign `+` and it also interfere with the game using shift key for something else (in-game menus).
would it be possible for `zoom in` and `zoom out` keys be added to the control configuration screen ?

update: same problem with "search" on starmap. i cannot search because to produce a `/` i must press `shift + :` on my keyboard.

**Comment by Serosis** [comment]
I'm not entirely sure menu keys can be changed like that in the menu.  

Although, you can change the keys in the `menu.key` file that's located where the content is.

**Comment by nsklaus** [comment]
with latest sources i can zoom fine using pageup/page down. also i see that as you told i can manually change keys through the menu.key. that problem i was having was tied to using old sources. i'm closing the issue.
