### ISSUE TITLE
voice and text out of sync

### ISSUE THREAD

**Issue by nsklaus** [JHGuitarFreak/UQM-MegaMod#50]
voice and text are out of sync. i tested this with building normal uqm and building uqm-mm.
on normal uqm: no problem
on uqm-mm: sync problem. 
this happens even if i choose all the lightweight options (original gfx, small resolution and so on)

my build environment is arch linux.

also it would be nice to be able to pause lenghty dialog to access game menu.
often i want to quit the game but i can't because i'm in the middle of a dialogue, i must follow through it all to be able to access the menu. when testing for bugs it is annoying. for example: i talk to fwiffo, first time. i notice text and voice are out of sync, i want to exit the game to change options (quit or disable voices or whatever) but i can't. i am forced to go through all fwiffo's dialogue first.

**Comment by Kruzen** [comment]
Hi. I'm not a mod dev so I can't help with desync problem, but you can press F10 at any point in time during dialog to quit the game. This will speed up your testing :)

**Comment by nsklaus** [comment]
@Kruzen 
i didn't know that. thanks for telling !

**Comment by Serosis** [comment]
Have you made sure that you are using the MegaMod's version of the 3DO voice files and not Core UQM's voice files?

**Comment by nsklaus** [comment]
@Serosis 
no, in fact it's the opposite. i'm certain it's the 3do voice file i'm using. 

(...fiddling with sources...)

it turned out that i had all sort of problems because i was using incorrect sources from a slightly outdated archive. all is well now, using latest sources and uqm-mm content and voices.
sorry about that.
