### ISSUE TITLE
Supox don't use valuable dialog line

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#56]
Supox have line that I was aware of but never been able to trigger. It's about Rainbow World.
Proof for this line: [http://www.sa-matra.net/quotes/supox/](url) 
```
Is there any knowledge which you alone possess?

Knowledge is the purview of the Utwig. We Supox are but the effectuators.
In truth though, we have learned a fact or two unknown to others
largely because we did not think anyone would care in the slightest, but since you ask, listen.
We have not fared far from our region of space, but we have explored this region thoroughly.
Of all the oddities we have found, from the firefalls of Nalnar to the servants of Mali
the truest mystery was the nature of a world we found at the orange star, Beta Leporis.
As a general rule, we prefer not to dwell in such long-wavelength regions
as the light lacks tang, but we were on a mapping mission. That was when we found the planet.
At first we thought our scanners had failed, for they showed us a world of chromatic aspect.
Then we located the source of our malfunction... the planet itself!
Somehow the planet generates a field of unusual radiations which scramble delicate circuitry.
Though blazing hot, we attempted a landing. Before we were forced off the surface by the intense heat
we registered the presence of huge amounts of processed radioactives.
Strange, is it not?
```
Ultronomicon article: [https://wiki.uqm.stack.nl/Firefalls_of_Nalnar](url)

I found these lines in code: it's _give_info_ and _GOOD_HINTS_ in Supox strings.h (_give_info_ also mentioned in yehat dialog but it's completely different line) but they **never used** in code. I replaced standart greeting with _GOOD_HINTS_ just to see it in game and it looks solid and in sync.

It would be nice to bring this line back in game, but as I said I never knew how to trigger it so no sertanty where to put it.
I tested Supox on UQM 0.7.0, MegaMod and PC-DOS version, but was unable to trigger it. Not a single youtube video feature that line.
Logically this line could be enabled when Supox becomes our allies after we give ultron to the Utwig, but that's just a guess.

**Comment by Serosis** [comment]
Added it in with commit 36608c1f0d4cc7e5850f32e889283821a58e363a
