### ISSUE TITLE
Dnyarri shenanigans before Sa-Matra attack

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#59]
Have 2 sub-issues:
1) Line `HELLO_AFTER_COMPEL_URQUAN` when you speak to him after he controls Ur-Quan off the screen and he freaks out on you, is **not voiced**.
I know re-voicing is a tricky thing so I don't sugget to do it hastly but maybe audio file is corrupted or something? Investigate at least for now should be enough.

2) After compelling Ur-Quan you **CAN** leave solar system without any downsides and do pretty much you like. Coding something fancy here could be difficult or almost impossible, but maybe create GameOver screen if we enter HyperSpace during `URQUAN_MESSED_UP = true`. I don't really mind to keep it as it is, it's just wierd that dnyarri stressed on that fact and you can simply ignore it.

**Comment by Serosis** [comment]
I wonder if I can make it so you *can't* leave the system once you enter it and activate the Dnyarri.

**Comment by Kruzen** [comment]
No simple and elegant way to fix that. Leaving it as it is now
