### ISSUE TITLE
Sa-Matra infinite fleet

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#60]
If we attack Sa-Matra without talking pet, we'll face infinite Ur-Quan fleet. However after Kohr-Ah start their movement, that infinite fleet swithes to Kohr-Ah fleet. But if we try to converse in that state - we'll still have Ur-Quan. I don't know how correct it is so it's up to discussion. 
But anyway possible solution to trigger Kohr-Ah here:

**gensam.c** function _GenerateSaMatra_generateOrbital (SOLARSYS_STATE *solarSys, PLANET_DESC *world)_

Instead of 
```
GLOBAL(CurrentActivity) |= START_INTERPLANETARY;
SET_GAME_STATE(GLOBAL_FLAGS_AND_DATA, 1 << 7);
SET_GAME_STATE(URQUAN_PROTECTING_SAMATRA, 1);
InitCommunication(URQUAN_CONVERSATION);
```
add
```
GLOBAL(CurrentActivity) |= START_INTERPLANETARY;
SET_GAME_STATE(GLOBAL_FLAGS_AND_DATA, 1 << 7);
SET_GAME_STATE(URQUAN_PROTECTING_SAMATRA, 1);
if (!GET_GAME_STATE(KOHR_AH_FRENZY) || GET_GAME_STATE(URQUAN_MESSED_UP))
	InitCommunication(URQUAN_CONVERSATION);
else
	InitCommunication(BLACKURQ_CONVERSATION);
```

**Comment by Serosis** [comment]
I added this into Extended Lore with commit 263691ef745a80f9990872f98aa475fb0a90b15c
