### ISSUE TITLE
Ilwrath survive after Thraddash war

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#61]
After Ilwrath's SOI disappears their homeworld is still populated and won't be destroyed by the Kohr-Ah either. Wasn't an issue in Core UQM or PC-DOS versions as I remember.

![image](https://user-images.githubusercontent.com/68859542/90799421-e0998100-e31b-11ea-920c-6d0310e5aa0c.png)

![image](https://user-images.githubusercontent.com/68859542/90799463-ee4f0680-e31b-11ea-8f60-5219aac3e122.png)

![image](https://user-images.githubusercontent.com/68859542/90799531-0757b780-e31c-11ea-839e-ecaa5bb44993.png)

If we keep them in place, Kohr-Ah annihilate them just fine.

**Comment by Serosis** [comment]
This was fixed awhile back with commit cd052114f9f316f2e6926c4c1e140671bb0e957f
