### ISSUE TITLE
Supox delayed demise

### ISSUE THREAD

**Issue by Kruzen** [JHGuitarFreak/UQM-MegaMod#63]
If we are in interplanetary of the home star of a race at the moment of it's destruction by Kohr-Ah, race's ships will still be in the system, because it can't be reloaded. But if we leave system and re-enter it, everything will vanish. 
Not a case for the Supox.
They keep spawning for about 2-3 weeks.

Even Utwig already destroyed:
![image](https://user-images.githubusercontent.com/68859542/90801246-543c8d80-e31e-11ea-8bf3-c1497b500d27.png)

I left and re-enter system:
![image](https://user-images.githubusercontent.com/68859542/90801286-61f21300-e31e-11ea-9693-771662965d38.png)

Retry, 9 days passed:
![image](https://user-images.githubusercontent.com/68859542/90801467-9796fc00-e31e-11ea-9d57-e13dd3d0de1d.png)

Retry, finally vanished:
![image](https://user-images.githubusercontent.com/68859542/90801581-c614d700-e31e-11ea-8a54-81b5827d2233.png)

Maybe it is a coincidence but they despawned when Kohr-Ah SOI moved away from the star.
I followed Kohr-Ah during all march. That issue is only Supox. BTW homeworld becomes empty right on day of destruction so it works completely fine.

**Comment by Kruzen** [comment]
Found that actually everyone is affected by it on EXTREMELY random pattern

**Comment by Serosis** [comment]
Does this happen with Core UQM?

**Comment by Kruzen** [comment]
This also happens in Core UQM. However it occurs only if you re-enter the same system you've been during race wipe. Entering any other system and then going back will despawn all of this race ships.
Overall this is a minor issue that occurs on a very specific scenario so I'm closing it.
