### ISSUE TITLE
Master build, Linux GCC linking error

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#65]
Hi,

I can't help but feel I'm doing something wrong, but then it didn't use to do this
The compiling gets stuck at the linking process

Any suggestions?

> 
> LINK     UrQuanMasters
> /usr/bin/ld: obj/release/src/libs/uio/io.c.o: in function `uio_transplantDir':
> io.c:(.text+0x25b): undefined reference to `_strdup'
> /usr/bin/ld: obj/release/src/libs/uio/match.c.o: in function `match_prepareContext':
> match.c:(.text+0x4e): undefined reference to `_strdup'
> /usr/bin/ld: match.c:(.text+0xd6): undefined reference to `_strdup'
> /usr/bin/ld: match.c:(.text+0x106): undefined reference to `_strdup'
> /usr/bin/ld: match.c:(.text+0x141): undefined reference to `_strdup'
> /usr/bin/ld: obj/release/src/libs/uio/match.c.o:match.c:(.text+0x550): more undefined references to `_strdup' follow
> /usr/bin/ld: obj/release/src/libs/uio/debug.c.o: in function `debugCmdCat.part.0':
> debug.c:(.text+0x10c9): undefined reference to `_fileno'
> /usr/bin/ld: obj/release/src/libs/uio/debug.c.o: in function `uio_debugInteractive':
> debug.c:(.text+0x124e): undefined reference to `_isatty'
> /usr/bin/ld: obj/release/src/libs/uio/stdio/stdio.c.o: in function `stdio_close':
> stdio.c:(.text+0x79): undefined reference to `_close'
> /usr/bin/ld: obj/release/src/libs/uio/stdio/stdio.c.o: in function `stdio_mount':
> stdio.c:(.text+0x11c): undefined reference to `_strdup'
> /usr/bin/ld: stdio.c:(.text+0x12d): undefined reference to `_strdup'
> /usr/bin/ld: obj/release/src/libs/uio/stdio/stdio.c.o: in function `stdio_getPDirEntryHandle':
> stdio.c:(.text+0x74b): undefined reference to `_strdup'
> /usr/bin/ld: obj/release/src/libs/uio/stdio/stdio.c.o: in function `stdio_mkdir':
> stdio.c:(.text+0x853): undefined reference to `_strdup'
> /usr/bin/ld: obj/release/src/libs/mikmod/load_it.c.o: in function `IT_Load':
> load_it.c:(.text+0x5d0): undefined reference to `_strdup'
> /usr/bin/ld: obj/release/src/libs/mikmod/load_it.c.o:load_it.c:(.text+0x97d): more undefined references to `_strdup' follow
> /usr/bin/ld: obj/release/src/uqm/encount.c.o: in function `UninitEncounter':
> encount.c:(.text+0x156e): undefined reference to `_strupr'
> /usr/bin/ld: obj/release/src/uqm/gameopt.c.o: in function `DrawGameSelection':
> gameopt.c:(.text+0x1b97): undefined reference to `strncpy_s'
> /usr/bin/ld: obj/release/src/uqm/gameopt.c.o: in function `PickGame':
> gameopt.c:(.text+0x28b7): undefined reference to `strncpy_s'
> /usr/bin/ld: obj/release/src/uqm/intro.c.o: in function `DoPresentation':
> intro.c:(.text+0x421): undefined reference to `_strupr'
> /usr/bin/ld: intro.c:(.text+0x17d7): undefined reference to `_strupr'
> /usr/bin/ld: obj/release/src/uqm/sis.c.o: in function `DrawFlagshipName':
> sis.c:(.text+0xd53): undefined reference to `_strupr'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile.build:88: UrQuanMasters] Error 1
>

**Comment by Serosis** [comment]
I fixed a bunch of Visual Studio warnings thinking that it would be parallel everywhere else.

Guess I'll have to revert it.

**Comment by Serosis** [comment]
Try it now, I just reverted commit 5dc46f27410928f6a765e107388aca830b1a0d0c

**Comment by JoshuaPettus** [comment]
Thanks!  Unfortunately there are still a couple more

> LINK     UrQuanMasters
> /usr/bin/ld: obj/release/src/uqm/gameopt.c.o: in function `DrawGameSelection':
> gameopt.c:(.text+0x1b97): undefined reference to `strncpy_s'
> /usr/bin/ld: obj/release/src/uqm/gameopt.c.o: in function `PickGame':
> gameopt.c:(.text+0x28b7): undefined reference to `strncpy_s'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile.build:88: UrQuanMasters] Error 1

**Comment by Serosis** [comment]
Stupid Windows only functions.

Fixed.

**Comment by JoshuaPettus** [comment]
Yup that did it!  Thanks!
