### ISSUE TITLE
4x main menu

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#66]
Hi,

I thought I'd try my hand at improving the 4x main menu a bit starting from an AI upscale of the 2x one, then using the text from the current one and a bit of blend.
What do you think?  It's not a huge improvement but might be a little better

Mine:
![newgame-000](https://user-images.githubusercontent.com/5043172/93956219-a3ac1a00-fd1f-11ea-87cc-cbee3eb9bca9.png)

Current:
![newgame-000](https://user-images.githubusercontent.com/5043172/93954679-364aba00-fd1c-11ea-9fe4-57e5524d50db.png)

**Comment by Serosis** [comment]
Hmmm...

I'll look into doing this.

**Comment by JoshuaPettus** [comment]
Absolutely!  didn't mean to take any of the fun from you :)

**Comment by Serosis** [comment]
I made my own variant with the latest commit over on the content repository: https://github.com/Serosis/UQM-MegaMod-Content/commit/d5028fd378e2f5b1aa5327447af67612dca4247a
