### ISSUE TITLE
Master build: Text a smidge too high in intro slides

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#68]
This is only for HD. In the intro slides, the text is a tad high.  Right up against the edge.  The same happens in conversations where the text is positioned on top.  This is the case for with and without the new classic hd font pack.

**Comment by Serosis** [comment]
Fixed this with commits 7111359ee973446fb4cc3d9fb34c3456582ab60e and 7b74d7b2b3af2f9125b950258b373bcb4ef3e2b0
