### ISSUE TITLE
No spathi text with classic-hd-fonts.uqm

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#69]
Right now with that add-on active when you talk to a spathi there is no font at all.  I would have thought the one in mm-hd would have shown instead if uqm couldn't find anything, but I guess not.

I noticed in the commits that you had pulled the spathi font.  Is it going to be replaced?

**Comment by Serosis** [comment]
I actually *just* fixed that with commit [06be41](https://github.com/Serosis/UQM-MegaMod-Content/commit/06be419bdaf848c6d46baf597ac92dbfbe23dd38)

But no, the Classic HD-mod font for the Spathi and ZFP is an officially licensed Adobe font: https://fonts.adobe.com/fonts/hobo
I'm trying to keep things above board now by using open licensed options or at the very least free for non-commercial use.

**Comment by JoshuaPettus** [comment]
Oh Doh! Sorry about that!

Good to know about the adobe font. In that case 100% agree.  I didn't realize they were the same for Spathi and ZFP.  They should have their own individual font anyway
