### ISSUE TITLE
Linux Compile of 0.8.0.85 cannot reach Setup menu

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#72]
Whenever I go to the setup menu, it immediately CTD

The console gets this
`PANIC: Incorrect number of Choice Options: 60. Should be 59
Segmentation fault (core dumped)
`
Ive tried it with our without any addons.  Let me know if you need any more information

**Comment by Serosis** [comment]
Why 0.8.0.83?

EDIT: Also look for residual content hiding elsewhere.

**Comment by JoshuaPettus** [comment]
Golly I must have been tired yesterday.... Can't get anything right....I had meant 0.8.0.85....lol asking you to bugfix an early version....

Nah there aren't any other packages mentioned in the console save the base content
Here is the entire console output from the start in case you are interested.

`'/usr/local/share/games/uqm-mmod/bin/UrQuanMasters' 
The Ur-Quan Masters v0.8.0.85 MegaMod (compiled Nov  7 2020 20:16:29)
This software comes with ABSOLUTELY NO WARRANTY;
for details see the included 'COPYING' file.

Netplay protocol version 0.4. Netplay opponent must have UQM 0.8.0.85 or later.

GCC_VERSION: 9.3.0

GCC_VERSION: 9.3.0

Buid Time: Nov  7 2020 20:16:29

Initializing base SDL functionality.
Using SDL version 2.0.10 (compiled with 2.0.10)
Using SDL version 2.0.10
Compiled with 2.0.10

Using config dir '/home/joshuapettus/.uqm-megamod/'
uio_getFileSystemHandler 0x55dc9f394440
Using '/usr/local/share/games/uqm-mmod/share/uqm-megamod/content' as base content dir.
uio_getFileSystemHandler 0x55dc9f394440
uio_open mm-0.8.0.85-content.uqm
uio_getFileSystemHandler 0x55dc9f3945e0
uio_open uqm-0.8.0.0.85-content.uqm
uio_getFileSystemHandler 0x55dc9f3945e0
0 available addon packs.
Saved games are kept in /home/joshuapettus/.uqm-megamod/save/.
Initializing SDL.
SDL initialized.
Initializing Screen.
SDL2 renderer 'opengl' selected.

1 joysticks were found.
The names of the joysticks are:
    Thrustmaster T.16000M
VControl opened joystick: Thrustmaster T.16000M
4 axes, 16 buttons, 1 hats.
OpenAL driver not compiled in, so using MixSDL
Initializing SDL audio subsystem.
SDL audio subsystem initialized.
Opening SDL audio device.
    using alsa at 44100 Hz 16 bit stereo, 4096 samples audio buffer
Initializing mixer.
Mixer initialized.
Initializing sound decoders.
Sound decoders initialized.
Loading resource index 'uqm.rmp'
Warning: Addon 'mm-hd' not found
Warning: Addon 'ProfanePkunk' not found
Warning: Addon '3dovoice' not found
Warning: Addon 'volasaurus-remix-pack' not found
Warning: Addon 'SpaceMusic' not found
	'base/uqm.ct' -- 104466 bytes
We've loaded the Kernel
Script directory 'base/script/initgame': loading 1 file(s).
Loading script 'initprops.lua'.
	'base/cutscene/logo/logo.txt' -- 309 bytes
	'base/ui/mainmenu1.ogg' -- 2425981 bytes
_GetMusicData(): loading base/ui/mainmenu1.ogg
    decoder: Ogg Vorbis, rate 44100 format 17
Loading HD Splashscreen

	'base/ui/hd/title.ani' -- 20 bytes
	'base/ships/arilou/skiff-icons.ani' -- 60 bytes
	'base/ships/arilou/skiff-meleeicons.ani' -- 481 bytes
	'base/ships/arilou/skiff.txt' -- 407 bytes
	'base/ships/chmmr/avatar-icons.ani' -- 60 bytes
	'base/ships/chmmr/avatar-meleeicons.ani' -- 69 bytes
	'base/ships/chmmr/avatar.txt' -- 353 bytes
	'base/ships/human/cruiser-icons.ani' -- 62 bytes
	'base/ships/human/cruiser-meleeicons.ani' -- 70 bytes
	'base/ships/human/cruiser.txt' -- 331 bytes
	'base/ships/orz/nemesis-icons.ani' -- 64 bytes
	'base/ships/orz/nemesis-meleeicons.ani' -- 600 bytes
	'base/ships/orz/nemesis.txt' -- 389 bytes
	'base/ships/pkunk/fury-icons.ani' -- 58 bytes
	'base/ships/pkunk/fury-meleeicons.ani' -- 465 bytes
	'base/ships/pkunk/fury.txt' -- 329 bytes
	'base/ships/shofixti/scout-icons.ani' -- 60 bytes
	'base/ships/shofixti/scout-meleeicons.ani' -- 482 bytes
	'base/ships/shofixti/scout.txt' -- 395 bytes
	'base/ships/spathi/eluder-icons.ani' -- 61 bytes
	'base/ships/spathi/eluder-meleeicons.ani' -- 502 bytes
	'base/ships/spathi/eluder.txt' -- 382 bytes
	'base/ships/supox/blade-icons.ani' -- 59 bytes
	'base/ships/supox/blade-meleeicons.ani' -- 483 bytes
	'base/ships/supox/blade.txt' -- 321 bytes
	'base/ships/thraddash/torch-icons.ani' -- 60 bytes
	'base/ships/thraddash/torch-meleeicons.ani' -- 484 bytes
	'base/ships/thraddash/torch.txt' -- 339 bytes
	'base/ships/utwig/jugger-icons.ani' -- 62 bytes
	'base/ships/utwig/jugger-meleeicons.ani' -- 502 bytes
	'base/ships/utwig/jugger.txt' -- 315 bytes
	'base/ships/vux/intruder-icons.ani' -- 66 bytes
	'base/ships/vux/intruder-meleeicons.ani' -- 536 bytes
	'base/ships/vux/intruder.txt' -- 249 bytes
	'base/ships/yehat/terminator-icons.ani' -- 70 bytes
	'base/ships/yehat/terminator-meleeicons.ani' -- 573 bytes
	'base/ships/yehat/terminator.txt' -- 425 bytes
	'base/ships/melnorme/trader-icons.ani' -- 61 bytes
	'base/ships/melnorme/trader-meleeicons.ani' -- 504 bytes
	'base/ships/melnorme/trader.txt' -- 369 bytes
	'base/ships/druuge/mauler-icons.ani' -- 61 bytes
	'base/ships/druuge/mauler-meleeicons.ani' -- 502 bytes
	'base/ships/druuge/mauler.txt' -- 333 bytes
	'base/ships/ilwrath/avenger-icons.ani' -- 62 bytes
	'base/ships/ilwrath/avenger-meleeicons.ani' -- 524 bytes
	'base/ships/ilwrath/avenger.txt' -- 365 bytes
	'base/ships/mycon/podship-icons.ani' -- 64 bytes
	'base/ships/mycon/podship-meleeicons.ani' -- 519 bytes
	'base/ships/mycon/podship.txt' -- 329 bytes
	'base/ships/slylandro/probe-icons.ani' -- 58 bytes
	'base/ships/slylandro/probe-meleeicons.ani' -- 67 bytes
	'base/ships/slylandro/probe.txt' -- 367 bytes
	'base/ships/umgah/drone-icons.ani' -- 60 bytes
	'base/ships/umgah/drone-meleeicons.ani' -- 482 bytes
	'base/ships/umgah/drone.txt' -- 367 bytes
	'base/ships/urquan/dreadnought-icons.ani' -- 71 bytes
	'base/ships/urquan/dreadnought-meleeicons.ani' -- 592 bytes
	'base/ships/urquan/dreadnought.txt' -- 425 bytes
	'base/ships/zoqfotpik/stinger-icons.ani' -- 64 bytes
	'base/ships/zoqfotpik/stinger-meleeicons.ani' -- 520 bytes
	'base/ships/zoqfotpik/stinger.txt' -- 367 bytes
	'base/ships/syreen/penetrator-icons.ani' -- 70 bytes
	'base/ships/syreen/penetrator-meleeicons.ani' -- 572 bytes
	'base/ships/syreen/penetrator.txt' -- 343 bytes
	'base/ships/kohrah/marauder-icons.ani' -- 64 bytes
	'base/ships/kohrah/marauder-meleeicons.ani' -- 538 bytes
	'base/ships/kohrah/marauder.txt' -- 429 bytes
	'base/ships/androsynth/guardian-icons.ani' -- 66 bytes
	'base/ships/androsynth/guardian-meleeicons.ani' -- 73 bytes
	'base/ships/androsynth/guardian.txt' -- 389 bytes
	'base/ships/chenjesu/broodhome-icons.ani' -- 66 bytes
	'base/ships/chenjesu/broodhome-meleeicons.ani' -- 76 bytes
	'base/ships/chenjesu/broodhome.txt' -- 369 bytes
	'base/ships/mmrnmhrm/xform-icons.ani' -- 58 bytes
	'base/ships/mmrnmhrm/xform-meleeicons.ani' -- 68 bytes
	'base/ships/mmrnmhrm/xform.txt' -- 395 bytes
	'base/fonts/starcon.fon' -- 1 bytes
	'base/fonts/starcon.fon' -- 1 bytes
	'base/fonts/tiny.fon' -- 1 bytes
	'base/fonts/tiny.fon' -- 1 bytes
	'base/fonts/player.fon' -- 1 bytes
libpng warning: iCCP: profile 'BenQ GL2706PQ Color Profile,D6500': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'BenQ GL2706PQ Color Profile,D6500': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'BenQ GL2706PQ Color Profile,D6500': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'BenQ GL2706PQ Color Profile,D6500': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'BenQ GL2706PQ Color Profile,D6500': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'BenQ GL2706PQ Color Profile,D6500': 0h: PCS illuminant is not D50
	'base/ui/border/border.ani' -- 593 bytes
	'base/ui/activity.ani' -- 259 bytes
	'base/ui/status.ani' -- 144 bytes
	'base/nav/nebulae/nebulae.ani' -- 1055 bytes
	'base/ui/submenu.ani' -- 154 bytes
	'base/gamestrings.txt' -- 18945 bytes
	'base/fonts/micro.fon' -- 1 bytes
	'base/ui/menu.snd' -- 69 bytes
_GetSoundBankData(): loading base/ui/menusnd01.wav
_GetSoundBankData(): decoded bytes 1971
_GetSoundBankData(): loading base/ui/menusnd02.wav
_GetSoundBankData(): decoded bytes 1955
_GetSoundBankData(): loading base/ui/menusnd03.wav
_GetSoundBankData(): decoded bytes 1576
_GetSoundBankData(): loading base/ui/menusnd04.wav
_GetSoundBankData(): decoded bytes 2399
_GetSoundBankData(): loading base/ui/menusnd05.wav
_GetSoundBankData(): decoded bytes 56450
	'base/battle/stars.ani' -- 66 bytes
Trying to get undefined resource 'graphics.starpoints'
Set Seed: 16807

Set Difficulty: Normal

Set Extended: False

Set Nomad: False


	'base/fonts/tiny.hd.fon' -- 1 bytes
	'base/fonts/player.hd.fon' -- 1 bytes
	'base/fonts/starcon.hd.fon' -- 1 bytes
	'base/fonts/starconlg.hd.fon' -- 1 bytes
	'base/ui/hd/newgame.ani' -- 186 bytes
libpng warning: iCCP: CRC error
	'base/ui/mainmenu1.ogg' -- 2425981 bytes
_GetMusicData(): loading base/ui/mainmenu1.ogg
    decoder: Ogg Vorbis, rate 44100 format 17
	'base/ui/setupmenu.txt' -- 17880 bytes
	'base/ui/hd/setupmenu.ani' -- 279 bytes
PANIC: Incorrect number of Choice Options: 60. Should be 59
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 417 requests (417 known processed) with 0 events remaining.
Do not know how to display an error box
`

**Comment by Serosis** [comment]
You do have a stray base content somewhere:

```
uio_getFileSystemHandler 0x55dc9f394440
uio_open mm-0.8.0.85-content.uqm
uio_getFileSystemHandler 0x55dc9f3945e0
uio_open uqm-0.8.0.0.85-content.uqm
uio_getFileSystemHandler 0x55dc9f3945e0
```

**Comment by JoshuaPettus** [comment]
Ah!  Thank-you!  I'm afraid it will be a few days before I can go check it.  But clearly this isn't a bug.

Thanks again!
