### ISSUE TITLE
Bug buying tech from Melonorme

### ISSUE THREAD

**Issue by adowns602316** [JHGuitarFreak/UQM-MegaMod#73]
I have bought the 1st piece of tech from the traders.  He then told me that was all that was available at the time.  Later, I returned and when I ask about buying tech the game crashes.

Current work-around is to enable All Tech under the Cheats menu.

**Comment by Serosis** [comment]
Which Melnorme?

What modes were the game in?

Did you load a save from an older version of UQM?

**Comment by adowns602316** [comment]
Which Melnorme?

I guess you mean which star system?  I tried it in 3 different giant star
systems.  Alpha Centauri, the green giant in the Orz space and the white
one below the Orz.

What modes were the game in?

I tried it with several variations with the same result.  HD and original
graphics, voices on and off, extended lore on and off.  I think that's all
I changed but each time I used the same save which may have affected it.
The original setting was everything on, HD graphics, voices, extended
lore.  None of the cheats were enabled.

Did you load a save from an older version of UQM?

No.  I started a fresh game using the .85 release.


Another oddity I found was that the portal to quasi space did not open on
the 17th of the month but I'm not sure if that's a glitch or something that
I haven't triggered yet in the game.  I don't really know what changes the
mod makes so that could be normal at this point.

I'm running it on an i7 using Windows 10.
Let me know what other information you need or if it's possible to get a
log of the crash.

Thanks for the quick response.  I appreciate it.

**Comment by Serosis** [comment]
Sounds like you're running in Hard Mode if the natural Quasi Portal hasn't shown up either.

I'll check that out.

**Comment by Serosis** [comment]
I wasn't able to re-create the crash but the rest of the bug is repeatable on my end.

Could you upload the save game affected so I can see if it crashes on my end?

UPDATE: Cancel that save upload, I was able to replicate the crash as well and have already fixed it. 
I'll drum up new release binaries in about an hour.

**Comment by Serosis** [comment]
Fixed with commit 49a09a2df9c5077779912913fff6de01d6fdff19

The release has been updated accordingly.

**Comment by adowns602316** [comment]
I see that you have marked this as fixed.  However, I am uploading the save
for you anyway.  I had to play through again but once I reached that point
it did crash the game again.

**Comment by Serosis** [comment]
Wait, it crashed even with the updated files?

**Comment by adowns602316** [comment]
I haven't redownload it yet.

**Comment by adowns602316** [comment]
It's working for me.

**Comment by Serosis** [comment]
Oh thank god.
