### ISSUE TITLE
[Idea] Separating the time dilation mod 

### ISSUE THREAD

**Issue by Wendigo326** [JHGuitarFreak/UQM-MegaMod#74]
Yo, I can't get a contact email, the UQM forum has technical difficulties preventing new users and github pretends to be like a monastery where residents take a holy vow of silence and can't use pms. 

My trouble is that your stand-alone time dilation mod is no longer available. If you still have this, could you please re-upload it? The megamod changes a bit too much for me as a new player.

**Comment by Serosis** [comment]
Everything in the MegaMod is toggleable.  
You can make it run just like Vanilla UQM with only the Time Dilation option enabled if you so wanted.

Just make sure everything in the Visual Options is turned off and same for the Advanced Options.  
Then enable the Time Dilation setting you want in the Cheat Options

![image](https://user-images.githubusercontent.com/4404965/105222733-bbe64700-5b0f-11eb-8c77-c870395a40b2.png)
![image](https://user-images.githubusercontent.com/4404965/105222753-c30d5500-5b0f-11eb-97c0-97d3e524984a.png)
![image](https://user-images.githubusercontent.com/4404965/105223024-1aabc080-5b10-11eb-8985-b2a6ecbaf9f0.png)

Though I believe I made Vanilla settings the default for fresh installations. So you may only need to check that they're all disabled.
