### ISSUE TITLE
Delta Vulpeculae missing the Orz *playground* with at least one seed

### ISSUE THREAD

**Issue by onpon4** [JHGuitarFreak/UQM-MegaMod#75]
Just trying this mod for the first time today, and I'm real impressed! Though I did encounter one bug with the seed changing feature: having set my seed to `66634`, there's no Orz \*playground\* where there should be one. Only a single planet appears in Delta Vulpeculae with that seed and it isn't counted as the \*playground\*. This means I can't get the Taalo device, so the only way I can win is by allowing the Kohr-Ah to annihilate the Umgah, which is kind of sad. :sweat_smile: It would also make the game unwinnable if I was using the "no death march" cheat.

🕵️

**Comment by Serosis** [comment]
Wow, nice call. 
I'll have to expand the parameters on the planet generation.

**Comment by Serosis** [comment]
Fixed this with commit ad00afa16cdacaa29c1c69e385b53325e6d41c85

Give the repository a pull and recompile.
