### ISSUE TITLE
Graphical glitch with the fade to black when giving Zex his beast

### ISSUE THREAD

**Issue by onpon4** [JHGuitarFreak/UQM-MegaMod#76]
I think I'll just explain this one with a screenshot:

![Screenshot from 2021-02-21 02-11-58](https://user-images.githubusercontent.com/2217995/108618236-6a6cf880-73ea-11eb-8c3f-f746fa802541.png)

Looks like something messed up here. :wink: I'm on Debian 10 "Buster" in case that matters. Compiled with OpenGL support I think (compilation options I used were mostly just the defaults). Using the HD mod, as you can see.

🕵️

**Comment by Serosis** [comment]
Fixed this with commit [50c18e6](https://github.com/Serosis/UQM-MegaMod-Content/commit/50c18e61ec53ed90ed270b8fce8f7c3e310f8b49) in the Content repository.

Redownload the affected content file and replace it with the new one.
