### ISSUE TITLE
Master Build - Pictogram menu text overlaps with help menu minerals

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#78]
I did a test build of the master branch along with pulling the latest content files from the repo as well.
When on a planet and the help menu for minerals pop ups, it overlaps with the text on the pictographic menu

**Comment by Serosis** [comment]
Yeah, they're supposed to show what the mineral values are *before* you land.

Unfortunately there's no room to do it any other way.
