### ISSUE TITLE
Android Version Can't Download MelnormeVoiceFix

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod#97]
I realize that the Android release is just a curiosity but thought you should know.  Feel free to close this 

For whatever reason it won't connect to
https://www.warpstormstudios.com/uqmmod/MelnormeVoiceFixMMAddon.uqm

Looking at his site I suspect it's because he doesn't use https://.  The link on the site is http://.

---------------------
On a side note, both of you should look into LetsEncrypt for your sites, it's free and once it is setup properly, you can practically forget about it.  I mean it's not absolutely vital for the nature of your site or anything, but google is suppose to treat you better. And again you can't beat the price.  Although that all depends on if you have actual access to the machine running the site or not

**Comment by Serosis** [comment]
Android version suffers from a litany of problems unfortunately. Though this one seems to be on me for not looking harder at the download URLs

If you want the revoicing I believe you need to clear the data and cache from the app, go through the initialization process again but don't select the revoicing, then download the package and copy it to the addon folder manually.
On my devices from the root of the main storage it's `Android/data/net.serosis.megamod/files/addons` 

Also my website has a free SSL certificate service from my host. Already set up.

**Comment by JoshuaPettus** [comment]
Thanks I'll give that a try!  I'll close this, as you say there are a litany of problems

As to your site, sorry, I got to the http version of your site via the links here on the github release page, and didn't realize that there was an https version as well.  Really your service should have an http -> https redirect and not offer an http version.
