### ISSUE TITLE
THRADDASH_BODY_COUNT is too small

### ISSUE THREAD

**Issue by TomiBelan** [JHGuitarFreak/UQM-MegaMod#99]
In hard mode, you must destroy 35 Thraddash. But THRADDASH_BODY_COUNT is only 5 bits. If you save the game when it is 32 or more, it will overflow and only the remainder modulo 32 will be saved.

**Comment by Serosis** [comment]
Oof. I guess that means it should be set to 30.

**Comment by Serosis** [comment]
Fixed with commit 42829465449679e9efe7cd63bffc560081338252

**Comment by TomiBelan** [comment]
Thanks! 🙂
